### ISSUE TITLE
Problem with appended classes in IE7

### ISSUE THREAD

**Issue by keld30** [zoltan-dulac/html5Forms.js#1]
There’s a very annoying bug in IE7, when you click on a form field, it changes it’s size because the script is appending some class names to the field but is not adding a space between the original class name and the webforms class name, therefore, breaking it…

For ex: 
input type=”text” class=”city html5-hasFocushtml5-hasFocushtml5-hasFocus html5-hasPlaceholderText”
then it becomes:
input type=”text” class=”cityhtml5-hasFocushtml5-hasFocushtml5-hasFocus html5-hasPlaceholderText”

no space between city and html5 classes.

**Comment by zoltan-dulac** [comment]
This has been fixed already (must have forgotten to comment on this way back when). Closing.
