### ISSUE TITLE
Doesn't always load, esp. in DOMContentLoaded mode

### ISSUE THREAD

**Issue by dleffler** [zoltan-dulac/html5Forms.js#11]
Using Firefox 19.0.2 on win7prox64, the widgets are only initialized if it happens to 'execute immediately' and not otherwise.

**Comment by zoltan-dulac** [comment]
I haven't been able to replicate this issue (this issue has been around for a while ... will make sure I update these more often).  Closing for now.  Feel free to open if you see this issue again
