### ISSUE TITLE
type=date and type=time not editable in chrome anymore

### ISSUE THREAD

**Issue by Kitzberger** [zoltan-dulac/html5Forms.js#13]
in chrome it's not possible to manually edit the date and time input fields anymore. it's only possible to use the up/down buttons respectively the calendar dropdown.

it looks like any pressed number key will be auto-removed immediately. maybe this is related to https://github.com/zoltan-dulac/html5Forms.js/issues/3 ?

remove the html5Forms.js library resolves this problem and I can use the browsers nativ date and time input field rendering, which works fine.

this is how I embed the whole thing:

    <script type="text/javascript" src="/fileadmin/layout/scripts/html5Forms.js/shared/js/modernizr.com/Modernizr-2.5.3.forms.js"></script>
    <script type="text/javascript"
        src="/fileadmin/layout/scripts/html5Forms.js/shared/js/html5Forms.js"
        data-webforms2-support="date,time"
        data-webforms2-force-js-validation="false"
        data-webforms2-force-js-date-picker="false"
        data-lang="en"></script>

**Comment by erutan** [comment]
This issue no longer occurs in Chrome 40 on OS X. Close?

**Comment by zoltan-dulac** [comment]
@erutan , @Kitzberger : Thanks for looking into this.  It does look like Chrome fixed this already, so yeah ... I'm closing.
