### ISSUE TITLE
Failure when no input+select+textarea

### ISSUE THREAD

**Issue by Javarome** [zoltan-dulac/html5Forms.js#15]
The setupExtraFeatures() code iterates on available input, select and textarea and sets a node for each. But if none is found node remains undefined and node.type is attempted on an undefined value. 

While some recent browsers will only display "Uncaught TypeError: Cannot read property 'type' of undefined", oldest ones will just stop on such a failure.

Moreover, the code indicates that this will occur unless at least one instance of each type (input, select and textarea) is found in the document.

It would be better if node is checked before the test and if start could not be called automatically (on a 'ready' event if fields are dynamically added)

**Comment by zoltan-dulac** [comment]
This has been fixed by #16 .  Closing.
