### ISSUE TITLE
Problems with required input on IE

### ISSUE THREAD

**Issue by whgibbo** [zoltan-dulac/html5Forms.js#19]
Hi,
I've been using Html5Forms.js for a while, good work :)

I have recently stubble over a problem with a required field.  I have take the example test patternRequired.html and made the following change from :

     <input type="text" name="fullName" value="" required="required" />

to:

    <input type="text" name="fullName" value="" required="required" oninvalid="this.setCustomValidity('blah2');" onvalid="this.setCustomValidity('');/>

as I wanted to change the message that was being displayed depending on the language of the user.

Now if you load the page on IE8 (or IE 12 but in IE8) mode and don't enter anything and press enter.  You will see the 'blah2' appear on the full name field. :)

Now enter some text into the fullname input and press enter again.  It now always displays the blah message and the only way to get rid of the message is to reload the page.  :(

Any ideas ?

Thanks

**Comment by zoltan-dulac** [comment]
@whgibbo Sorry for the late response.  I'll be looking into these issues on github a lot more closely than I have of late.

It is better to use the `data-errormessage` attribute to set custom messages, like:
```html
<input type="text" name="fullName" value="" required="required" data-errormessage="Please enter your name to continue" />
```

Hope this helps.
