### ISSUE TITLE
Breaks Chrome input type=date

### ISSUE THREAD

**Issue by kingjeffrey** [zoltan-dulac/html5Forms.js#3]
The html5Forms.js addition of `step="undefined"` to input type=date causes all dates in Chrome's native drop down (Version 20.0.1132.47) to be unselectable.

**Comment by erutan** [comment]
FYI the test case page (http://test.kingdesk.com/date-input/) works fine in current chrome on OS X.

**Comment by zoltan-dulac** [comment]
@kingjeffrey , @erutan :  Thanks for your work looking into this.  Yeah -- it seems like Google fixed this in Chrome already, so I guess we can close this.  I'll take a look at #13 as well and if it's the same, I'll close that as well.
